### ISSUE TITLE
Is the "Z" mandatory at the end?

### ISSUE THREAD

**Issue by germanger** [Ins87/angular-date-interceptor#2]
From the server I'm getting a JSON like this:

       $scope.foo = {
              utcDate: "2017-04-05T00:00:00Z",
              localDate: "2017-04-05T00:00:00"
       };

(Recall that a Z at the end means that the date is in UTC)

I'm trying to show both dates in datepickers:

    <p class="input-group">
        <input type="text" class="form-control input-sm" ng-readonly="true" datepicker-options="datePickerOptions" uib-datepicker-popup="yyyy-MM-dd" ng-model="foo.utcDate" is-open="datePicker1IsOpen" />
        <span class="input-group-btn">
            <button type="button" class="btn btn-default btn-sm" ng-click="openDatePicker1($event)"><i class="glyphicon glyphicon-calendar"></i></button>
        </span>
    </p>

    <p class="input-group">
        <input type="text" class="form-control input-sm" ng-readonly="true" datepicker-options="datePickerOptions" uib-datepicker-popup="yyyy-MM-dd" ng-model="foo.localDate" is-open="datePicker2IsOpen" />
        <span class="input-group-btn">
            <button type="button" class="btn btn-default btn-sm" ng-click="openDatePicker2($event)"><i class="glyphicon glyphicon-calendar"></i></button>
        </span>
    </p>

But `localDate` is not being parsed to date... apparently.

Is the Z mandatory in `angular-date-interceptor` to be parsed?

**Comment by janosgy** [comment]
You are right.
Check it with the new version, it should be fixed now
